version: '3'

services:
  app_api:
    image: cancerlog.api:latest
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - backend

  db_api:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db_api
    ports:
      - ${API_PGA_PORT:-80}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${API_PGA_USER:-pgadmin}
      PGADMIN_DEFAULT_PASSWORD: ${API_PGA_PASSWORD:-pgadmin}
    networks:
      - backend

networks:
  backend:
