version: '3.7'

networks:
  feelback:

services:
  feelback-gateway:
    image: jwilder/nginx-proxy:alpine
    container_name: feelback-gateway
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - feelback

  feelback-web:
    container_name: feelback-web
    networks:
      - feelback
    environment:
      VIRTUAL_HOST: ${URI_ROOT},${URI_WWW}
      VIRTUAL_PORT: 80

  feelback-api:
    container_name: 'feelback-api'
    depends_on:
      - feelback-db
      - identity-db
    environment:
      VIRTUAL_HOST: ${URI_API}
      VIRTUAL_PORT: ${FB_API_PORT}
    ports:
      - ${FB_API_PORT}:${FB_API_PORT}
    networks:
      - feelback

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'feelback-pgadmin'
    depends_on:
      - feelback-db
      - identity-db
    ports:
      - ${PGA_PORT}:80
    networks:
      - feelback

  feelback-db:
    image: postgres:11-alpine
    container_name: 'feelback-db-feelback'
    networks:
      - feelback

  identity-db:
    image: postgres:11-alpine
    container_name: 'feelback-db-identity'
    networks:
      - feelback

  keycloak-db:
    image: postgres:11-alpine
    container_name: 'feelback-db-keycloak'
    networks:
      - feelback

  keycloak:
    image: jboss/keycloak:10.0.1
    container_name: 'feelback-keycloak'
    depends_on:
      - keycloak-db
    volumes:
      - ./docker/keycloak/realms:/opt/jboss/keycloak/imports
    command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/feelback.realm.json -Dkeycloak.migration.strategy=IGNORE_EXISTING
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      VIRTUAL_HOST: ${URI_AUTH}
      VIRTUAL_PORT: 8080
    networks:
      - feelback
