version: '3'

services:
  app_identity:
    build:
      context: .
      dockerfile: identity.Dockerfile
    ports:
      - ${ID_API_PORT}:${ID_API_PORT}
    networks:
      - backend

  db_identity:
    image: postgres:11-alpine
    ports:
      - ${ID_DB_PORT:-5433}:5432
    environment:
      POSTGRES_DB: ${ID_DB_NAME:-postgres}
      POSTGRES_USER: ${ID_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ID_DB_PASSWORD:-postgres}
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db_identity
    ports:
      - ${ID_PGA_PORT:80}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ID_PGA_USER:-pgadmin}
      PGADMIN_DEFAULT_PASSWORD: ${ID_PGA_PASSWORD:-pgadmin}
    networks:
      - backend

networks:
  backend:
