version: '3'

services:
  main_app:
    image: cancerlog.api:latest
    container_name: 'fb_main_api'
    ports:
      - ${FB_API_PORT}:${FB_API_PORT}
    networks:
      - backend

  main_db:
    image: postgres:11-alpine
    container_name: 'fb_main_db'
    environment:
      POSTGRES_DB: ${FB_DB_NAME:-postgres}
      POSTGRES_USER: ${FB_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${FB_DB_PASSWORD:-postgres}
    networks:
      - backend

  identity_db:
    image: postgres:11-alpine
    container_name: 'fb_identity_db'
    environment:
      POSTGRES_DB: ${ID_DB_NAME:-postgres}
      POSTGRES_USER: ${ID_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ID_DB_PASSWORD:-postgres}
    networks:
      - backend

  keycloak:
    image: jboss/keycloak:9.0.0
    container_name: 'fb_keycloak'
    depends_on:
      - keycloak_db
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_db
      DB_DATABASE: ${KEYCLOAK_DB_NAME:-keycloak}
      DB_USER: ${KEYCLOAK_DB_USER:-postgres}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-postgres}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-keycloak}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-keycloak}
      KEYCLOAK_LOGLEVEL: INFO
      PROXY_ADDRESS_FORWARDING: 'true'
    volumes:
      - .deployment/keycloak/feelback.realm-export.json:/opt/jboss/keycloak/imports/feelback.realm-export.json
    command:
      - '-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/feelback.realm-export.json'
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
    networks:
      - backend

  keycloak_db:
    image: postgres:11-alpine
    container_name: 'fb_keycloak_db'
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-postgres}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-postgres}
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'fb_pgadmin'
    depends_on:
      - main_db
      - identity_db
    ports:
      - ${PGA_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_USER:-pgadmin}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD:-pgadmin}
    networks:
      - backend

  web:
    container_name: fb_web
    build: ./apps/feelback-web
    volumes:
      - ./dist/apps/feelback-web:/usr/share/nginx/html/dist
      - ./dist/apps/feelback-web:/var/www/html/dist
      - ./apps/feelback-web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      - backend

networks:
  backend:
