query getPatients{
  myself {
    id
    email
    organizations {
      edges {
        node {
          id
          name
          members {
            edges {
              node {
                id
                firstname
                lastname
              }
            }
          }
        }
      }
    }
  }
}
