query getPatients {
  myself {
    id
    email
    organizations {
      edges {
        node {
          id
          name
          people {
            edges {
              node {
                id
                pseudonym
              }
            }
          }
        }
      }
    }
  }
}
