query getInstruments($paging:CursorPaging={first: 5}) {
  instruments(paging:$paging) {
    pageInfo {
      hasNextPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        name
        description
        type
        image
        createdAt
        updatedAt
        version
      }
    }
  }
}