query getScreeningsForPersonAndInstrument($paging:CursorPaging={first: 5})
{
  screeningsForPersonAndInstrument(
    paging:$paging
    personId: "2b3f4524-773d-4a2a-a576-ace6cfc4d7f3"
    instrumentId: "53f2a7c3-9c37-4a52-9194-8a3186af6f57"
  ) {
    pageInfo {
      hasNextPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        createdAt
        instanceId
        payload
        evaluationResult{name condition then else result}
      }
    }
  }
}
