query getScreeningsDiagramCollections(
  $personId: String!
  $instrumentId: String!
  $from: DateTime!
  $end: DateTime!
) {
  screeningsDiagramCollections(
    personId: $personId
    instrumentId: $instrumentId
    sorting: {field: collectedAt, direction:ASC},
    filter: {collectedAt: {between: {lower:$from, upper:$end}}}
  ) {
    name
    type
    axis {
      name
      data {
        screeningId
        x
        y
      }
    }
  }
}
