query getIdentities($paging: CursorPaging = {}) {
  identities(paging: $paging) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        id
        pseudonym
        title
        firstname
        lastname
      }
    }
  }
}


query getIdentityById($id: ID!) {
  identity(id:$id) {
    id
    pseudonym
    title
    firstname
    lastname
  }
}

mutation createOneIdentity($pseudonym: String!) {
  createOneIdentity(input: { 
    identity: {
      pseudonym: $pseudonym 
    }
  }) {
    id
    pseudonym
  }
}
