query identities {
  identities {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        id
        pseudonym
        title
        firstname
        lastname
      }
    }
  }
}

mutation createOneIdentity($pseudonym: String!) {
  createOneIdentity(input: { 
    pseudonym: $pseudonym 
  }) {
    id
    pseudonym
  }
}
