query getOrganizations($pagination: CursorPaging = { first: 10 }) {
  organizations(paging: $pagination) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        id
        name
        description
        type
        address
        phone
        email
        url
        logo
      }
    }
  }
}
