query getInstruments($pagination: CursorPaging = { first: 10 }) {
  instruments(paging: $pagination) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        name
        description
        type
        image
        payload
        changelog
      }
    }
  }
}
